---
apiVersion: v1
kind: Service
metadata:
  name: aws-es-auth-proxy
  namespace: aws-es-auth-proxy
  labels:
    name: aws-es-auth-proxy
    role: web
spec:
  ports:
  - port: 443 # Service opened port.
    protocol: TCP
    targetPort: 3000 # Endpoint of Pod
  selector:
    name: aws-es-auth-proxy
    role: web
  type: LoadBalancer
