---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aws-es-auth-proxy
  namespace: aws-es-auth-proxy
  labels:
    name: aws-es-auth-proxy
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      name: aws-es-auth-proxy
      labels:
        name: aws-es-auth-proxy
        role: web
    spec:
      containers:
      - image: quay.io/dtan4/aws-sign-proxy
        name: aws-signing-proxy
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: aws-secret-access-key
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: aws-region
        - name: AWS_SIGN_PROXY_SERVICE_NAME
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: aws-sign-proxy-service-name
        - name: AWS_SIGN_PROXY_UPSTREAM_HOST
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: aws-sign-proxy-upstream-host
      - image: quay.io/dtan4/nginx-basic-auth-proxy
        name: nginx-basic-auth-proxy
        ports:
        - containerPort: 80
        env:
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: basic-auth-username
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: basic-auth-password
        - name: PROXY_PASS
          value: http://localhost:8080/
        - name: SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: server-name
